import { z } from 'zod';

import {
    ERequirementFormat,
    ERequirementLevel,
    ERequirementPriority,
    ERequirementStatus,
    Json,
    Requirement,
} from '@/types';

export const RequirementSchema = z.object({
    id: z.string(),
    ai_analysis: z.any().nullable() as z.ZodType<Json>,
    block_id: z.string(),
    created_at: z.string().nullable(),
    created_by: z.string().nullable(),
    deleted_at: z.string().nullable(),
    deleted_by: z.string().nullable(),
    description: z.string().nullable(),
    document_id: z.string(),
    enchanced_requirement: z.string().nullable(),
    external_id: z.string().nullable(),
    format: z.enum([
        'incose',
        'ears',
        'other',
    ]) as z.ZodType<ERequirementFormat>,
    is_deleted: z.boolean().nullable(),
    level: z.enum([
        'component',
        'system',
        'subsystem',
    ]) as z.ZodType<ERequirementLevel>,
    name: z.string(),
    original_requirement: z.string().nullable(),
    priority: z.enum([
        'low',
        'medium',
        'high',
        'critical',
    ]) as z.ZodType<ERequirementPriority>,
    status: z.enum([
        'active',
        'archived',
        'draft',
        'deleted',
        'in_review',
        'in_progress',
        'approved',
        'rejected',
    ]) as z.ZodType<ERequirementStatus>,
    tags: z.array(z.string()).nullable(),
    type: z.string().nullable(),
    updated_at: z.string().nullable(),
    updated_by: z.string().nullable(),
    version: z.number(),
    position: z.number(),
    data: z.record(z.string(), z.any()).nullable().optional(),
    properties: z.any().nullable() as z.ZodType<Json | null>,
}) satisfies z.ZodType<Requirement>;
